player_number = 2
player_names = ["Player 1", "Player 2", "Player 3", "Player 4"]
players_colors = ["yellow", "red", "blue", "green"]
extra_bomb = True
extra_bomb_chance = 2
map_type = None
box_chance = 70
players_colors_values = [0, 1, 2, 3]
modifiers = True
